name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: zulu@1.11
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 '; set javaOptions := Seq("-Dtest.prop.minSuccessful=10000", "-Dtest.prop.sizeRange=10000"); test'
